# Generated by Django 5.1.2 on 2024-11-18 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='state',
        ),
        migrations.RemoveField(
            model_name='requestblood',
            name='state',
        ),
    ]
